name: 'Ansible'

on:
  workflow_run:
    workflows:
      - Terraform
    types: 
      - completed
    branches:
      - main
    
jobs:
  mysql:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: terrafrom.yml
          workflow_conclusion: success
          name: terraform