name: 'download'

on:
  workflow_run:
    workflows:
      - terraform
    types: 
      - completed
    branches:
      - main
    
jobs:
  docker:
    name: 'download'
    runs-on: Ubuntu-20.04
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: terraform.yml
          workflow_conclusion: success
          name: terraform_art
          path: terraform.log