name: 'download'

on:
  workflow_run:
    workflows:
      - terraform
    types: 
      - completed
    branches:
      - main
    
jobs:
  art:
    name: Download artifact
    uses: dawidd6/action-download-artifact@v2
    with:
      # Optional, GitHub token
      github_token: ${{secrets.GITHUB_TOKEN}}
      # Required, workflow file name or ID
      workflow: terraform.yml
      # Optional, the status or conclusion of a completed workflow to search for
      # Can be one of a workflow conculsion::
      # "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
      # Or a workflow status:
      # "completed", "in_progress", "queued"
      # Default: "completed"
      workflow_conclusion: success
      name: terraform
      # Optional, directory where to extract artifact
      path: terraform.log
      # Optional, defaults to current repo
      repo: ${{github.repository}}